name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustc --version
        cargo --version
        rustup install 1.81.0
        rustup default 1.81.0
        rustup target add wasm32-unknown-unknown
        cargo install --locked cargo-concordium
        cd ${{ github.workspace }}
        cd gona-token
        cargo concordium build -e --out dist/module.wasm.v1

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: dist/module.wasm.v1